import os
import json
from datetime import datetime
import logging

class TicketWriter:
    def __init__(self):
        # Creates a dedicated folder just for enterprise tickets
        self.output_dir = "enterprise_tickets"
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_ticket(self, target_domain, vulnerabilities):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_domain = target_domain.replace(".", "_")
        filename = f"JIRA_TICKET_{safe_domain}_{timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)

        ticket_content = f"# 🎫 INTERNAL REMEDIATION TICKET: {target_domain}\n"
        ticket_content += f"**Date Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        ticket_content += f"**Generated By:** Project Trishul (Virtual Security Engineer Mode)\n\n"
        ticket_content += "---\n\n"

        for vuln in vulnerabilities:
            try:
                # Nuclei outputs raw JSON, so we parse it to extract the juicy details
                data = json.loads(vuln)
                info = data.get("info", {})
                
                name = info.get("name", "Unknown Vulnerability")
                severity = info.get("severity", "info").upper()
                url = data.get("matched-at", "Unknown URL")
                desc = info.get("description", "No description provided by scanner.")
                remediation = info.get("remediation", "Investigate the endpoint and apply standard security patching.")
                
                # Map standard severity to Enterprise Jira Priority rankings
                priority = "P4 / Low"
                if severity == "CRITICAL": priority = "P1 / Highest"
                elif severity == "HIGH": priority = "P2 / High"
                elif severity == "MEDIUM": priority = "P3 / Medium"

                # 🚀 ENTERPRISE UPGRADE: Compliance Mapping 🚀
                compliance_impact = "Standard patching required."
                tags = info.get("tags", [])
                
                # If tags is a string (sometimes Nuclei outputs it as a string instead of a list), convert it
                if isinstance(tags, str):
                    tags = tags.split(",")
                
                if any("cve" in t for t in tags): 
                    compliance_impact = "🔴 VIOLATES SOC2 CC6.6 (Vulnerability Management) & ISO-27001 A.12.6.1"
                elif any("default" in t or "panel" in t for t in tags): 
                    compliance_impact = "🔴 VIOLATES SOC2 CC6.3 (Access Controls) & GDPR Article 32"
                elif any("misconfig" in t for t in tags): 
                    compliance_impact = "🟡 VIOLATES ISO-27001 A.14.1.1 (Security Requirements)"

                ticket_content += f"## [ISSUE] {name}\n"
                ticket_content += f"**Assignee:** Backend/DevOps Engineering Team\n"
                ticket_content += f"**Priority:** {priority} ({severity})\n"
                ticket_content += f"**Compliance Impact:** {compliance_impact}\n\n"
                
                ticket_content += f"### 📝 Description\n"
                ticket_content += f"Project Trishul detected a security misconfiguration/vulnerability during an authenticated internal audit.\n"
                ticket_content += f"> {desc}\n\n"
                
                ticket_content += f"### 📍 Vulnerable Endpoint\n"
                ticket_content += f"`{url}`\n\n"
                
                ticket_content += f"### 🛠️ Remediation Instructions\n"
                ticket_content += f"{remediation}\n\n"
                
                ticket_content += "---\n\n"

            except json.JSONDecodeError:
                logging.warning("Failed to parse vulnerability JSON for ticket generation.")
                continue

        with open(filepath, "w") as f:
            f.write(ticket_content)

        return filepath
